### PR TITLE
Use source commit in PR

### PR DESCRIPTION
**Pull request by jarimatti**
The source commit is IMHO a bit more useful than destination when working with pull requests by default.
Note that this builds on top of nikolauska's JSON PR #2 : I can rebase/cleanup this when that has been merged.

### CODE REVIEW

**Comment by lukepatrick** [comment]
Thanks. I've merged in #2, can you rebase/cleanup on this PR?

**Comment by jarimatti** [comment]
Excellent, thanks! I will do the cleanup later today.

**Comment by jarimatti** [comment]
Done: I did a rebase on master and force pushed it to my branch: everything seems to be in order. Note that I did not change the merged PR case, as it seemed logical to use destination in that case.
Please let me know if something is not correct.

**Comment by lukepatrick** [comment]
Looks good to me. Thank you for the contribution!

**Pull request merged**
